In [1]:
import numpy as np

In [19]:
data = np.load('0.025_sirs_infection_heatmap_data.npz')

In [20]:
data

NpzFile '0.025_sirs_infection_heatmap_data.npz' with keys: heatmap_data, S_vales, R_values

In [21]:
S = data['S_vales']
R = data['S_vales']
heatmap = data['heatmap_data']

In [26]:
heatmap[16]

array([0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.000506 ,
       0.0075444, 0.0377208, 0.1002508, 0.1295864, 0.1545124, 0.1787688,
       0.1932908, 0.204756 , 0.2223036, 0.2321484, 0.239764 , 0.2499228,
       0.2595184, 0.2637024, 0.2706596, 0.2772312, 0.2833856, 0.2877888,
       0.293912 , 0.2974328, 0.3008248, 0.3061552, 0.3093976, 0.3140272,
       0.3172424, 0.3210468, 0.3231872, 0.3259188, 0.3278732])

In [11]:
times

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [12]:
speed

array(0.42335651)

In [13]:
distance

array([ 0.44823351,  0.84671301,  1.29494653,  1.69342603,  2.14165954,
        2.54013904,  2.98837256,  3.38685206,  3.83508557,  4.23356507,
        4.68179858,  5.08027808,  5.5285116 ,  5.9269911 ,  6.37522461,
        6.77370411,  7.22193763,  7.62041713,  8.06865064,  8.46713014,
        8.91536365,  9.31384315,  9.76207667, 10.16055617, 10.60878968,
       11.00726918, 11.4555027 , 11.8539822 , 12.30221571, 12.70069521,
       13.14892872, 13.54740822, 13.99564174, 14.39412124, 14.84235475,
       15.24083425, 15.68906777, 16.08754727, 16.53578078, 16.93426028,
       17.38249379, 17.78097329, 18.22920681, 18.62768631, 19.07591982,
       19.47439932, 19.92263283, 20.32111234, 20.76934585, 21.16782535,
       21.61605886, 22.01453836, 22.46277188, 22.86125138, 23.30948489,
       23.70796439, 24.1561979 , 24.5546774 , 25.00291092, 25.40139042,
       25.84962393, 26.24810343, 26.69633695, 27.09481645, 27.54304996,
       27.94152946, 28.38976297, 28.78824247, 29.23647599, 29.63

In [16]:
y

array(0.43592065)